-- Generated by go run ./services/document/cmd/atlas
CREATE TABLE "documents" (
  "document_id" uuid,
  "display_name" text NOT NULL,
  "content" bytea NOT NULL,
  "created_at" timestamptz,
  "updated_at" timestamptz,
  PRIMARY KEY ("document_id")
);
